import { defineManifest } from "@crxjs/vite-plugin";

export default defineManifest({
  manifest_version: 3,
  name: "Chat2Notion",
  description: "Sync AI questions and answers to a Notion database.",
  version: "0.3.2",
  action: {
    default_title: "Chat2Notion",
    default_popup: "src/popup/popup.html",
  },
  options_page: "src/popup/popup.html",
  background: {
    service_worker: "src/background/background.ts",
    type: "module",
  },
  permissions: ["storage", "activeTab"],
  host_permissions: [
    "https://chatgpt.com/*",
    "https://chat.openai.com/*",
    "https://gemini.google.com/*",
    "https://bard.google.com/*",
    "https://chat.deepseek.com/*",
    "https://claude.ai/*",
    "https://perplexity.ai/*",
    "https://www.perplexity.ai/*",
    "https://copilot.microsoft.com/*",
    "https://www.bing.com/*",
    "https://poe.com/*",
    "https://www.poe.com/*",
    "https://chat.mistral.ai/*",
    "https://mistral.ai/*",
    "https://meta.ai/*",
    "https://www.meta.ai/*",
    "https://doubao.com/*",
    "https://www.doubao.com/*",
    "https://*.doubao.com/*",
    "https://kimi.moonshot.cn/*",
    "https://kimi.com/*",
    "https://www.kimi.com/*",
    "https://chat.qwen.ai/*",
    "https://qwen.ai/*",
    "https://tongyi.aliyun.com/*",
    "https://qianwen.aliyun.com/*",
    "https://www.qianwen.com/*",
    "https://yuanbao.tencent.com/*",
    "https://chatglm.cn/*",
    "https://www.chatglm.cn/*",
    "https://chatglm.com/*",
    "https://chat.z.ai/*",
    "https://yiyan.baidu.com/*",
    "https://chat.baidu.com/*",
    "https://wenxin.baidu.com/*",
    "https://huggingface.co/chat/*",
    "https://duck.ai/*",
    "https://duckduckgo.com/*",
    "https://you.com/*",
    "https://www.you.com/*",
    "https://grok.com/*",
    "https://*.grok.com/*",
    "https://x.com/i/grok*",
    "https://api.notion.com/*",
  ],
  content_scripts: [
    {
      matches: [
        "https://chatgpt.com/*",
        "https://chat.openai.com/*",
        "https://gemini.google.com/*",
        "https://bard.google.com/*",
        "https://chat.deepseek.com/*",
        "https://claude.ai/*",
        "https://perplexity.ai/*",
        "https://www.perplexity.ai/*",
        "https://copilot.microsoft.com/*",
        "https://www.bing.com/*",
        "https://poe.com/*",
        "https://www.poe.com/*",
        "https://chat.mistral.ai/*",
        "https://mistral.ai/*",
        "https://meta.ai/*",
        "https://www.meta.ai/*",
        "https://doubao.com/*",
        "https://www.doubao.com/*",
        "https://*.doubao.com/*",
        "https://kimi.moonshot.cn/*",
        "https://kimi.com/*",
        "https://www.kimi.com/*",
        "https://chat.qwen.ai/*",
        "https://qwen.ai/*",
        "https://tongyi.aliyun.com/*",
        "https://qianwen.aliyun.com/*",
        "https://www.qianwen.com/*",
        "https://yuanbao.tencent.com/*",
        "https://chatglm.cn/*",
        "https://www.chatglm.cn/*",
        "https://chatglm.com/*",
        "https://chat.z.ai/*",
        "https://yiyan.baidu.com/*",
        "https://chat.baidu.com/*",
        "https://wenxin.baidu.com/*",
        "https://huggingface.co/chat/*",
        "https://duck.ai/*",
        "https://duckduckgo.com/*",
        "https://you.com/*",
        "https://www.you.com/*",
        "https://grok.com/*",
        "https://*.grok.com/*",
        "https://x.com/i/grok*",
      ],
      js: ["src/content/content.ts"],
      run_at: "document_idle",
      all_frames: true,
    },
  ],
});
