export interface PlatformAdapter {
  id: string;
  aiName: string;
  hosts: string[];
  assistantSelectors: string[];
  userSelectors: string[];
  contentSelectors: string[];
  assistantArticlePattern: RegExp;
  userArticlePattern: RegExp;
  streamingSelectors: string[];
}

export const PLATFORM_ADAPTERS: PlatformAdapter[] = [
  {
    id: "chatgpt",
    aiName: "ChatGPT",
    hosts: ["chatgpt.com", "chat.openai.com"],
    assistantSelectors: ['[data-message-author-role="assistant"]'],
    userSelectors: ['[data-message-author-role="user"]'],
    contentSelectors: [".markdown", "[data-message-content]", "[data-testid='conversation-turn-message']"],
    assistantArticlePattern: /assistant|chatgpt/i,
    userArticlePattern: /user|you/i,
    streamingSelectors: [
      '[data-testid="stop-button"]',
      '[aria-label*="Stop"]',
      '[aria-label*="停止"]',
      ".result-streaming",
    ],
  },
  {
    id: "gemini",
    aiName: "Gemini",
    hosts: ["gemini.google.com", "bard.google.com"],
    assistantSelectors: [
      "model-response",
      "[data-testid='model-response']",
      "[data-test-id='model-response']",
      ".model-response",
    ],
    userSelectors: ["user-query", "[data-testid='user-query']", "[data-test-id='user-query']", ".user-query"],
    contentSelectors: [".markdown", "message-content", ".message-content", ".response-content", ".query-text"],
    assistantArticlePattern: /assistant|gemini|model|response/i,
    userArticlePattern: /user|you|query|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', ".stop-button"],
  },
  {
    id: "deepseek",
    aiName: "DeepSeek",
    hosts: ["chat.deepseek.com"],
    assistantSelectors: [
      ".ds-virtual-list-visible-items > ._4f9bf79",
      "._4f9bf79",
      "._43c05b5",
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      ".ds-markdown",
      "[class*='assistant']",
    ],
    userSelectors: [
      ".ds-virtual-list-visible-items > ._9663006",
      "._9663006",
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
    ],
    contentSelectors: [".ds-markdown", ".markdown", "[class*='markdown']", "[class*='content']"],
    assistantArticlePattern: /assistant|deepseek|answer|response/i,
    userArticlePattern: /user|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "claude",
    aiName: "Claude",
    hosts: ["claude.ai"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-testid*='assistant']",
      "[data-testid*='message']",
      ".assistant-message",
      "[class*='assistant']",
      "[class*='font-claude-message']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-testid*='user']",
      "[data-testid*='message']",
      ".user-message",
      "[class*='user']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='font-claude-message']",
      "[class*='message']",
      "[class*='content']",
    ],
    assistantArticlePattern: /assistant|claude|response/i,
    userArticlePattern: /user|you|human|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "grok",
    aiName: "Grok",
    hosts: ["grok.com", "x.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
    ],
    contentSelectors: [".markdown", "[class*='markdown']", "[class*='message']", "[class*='content']"],
    assistantArticlePattern: /assistant|grok|answer|response/i,
    userArticlePattern: /user|you|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "perplexity",
    aiName: "Perplexity",
    hosts: ["perplexity.ai", "www.perplexity.ai"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-testid*='answer']",
      "[data-testid*='assistant']",
      "[class*='answer']",
      "[class*='prose']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-testid*='query']",
      "[data-testid*='question']",
      "[class*='query']",
      "[class*='question']",
    ],
    contentSelectors: [
      ".prose",
      ".markdown",
      "[class*='prose']",
      "[class*='markdown']",
      "[class*='answer']",
      "[class*='content']",
    ],
    assistantArticlePattern: /assistant|answer|response|perplexity/i,
    userArticlePattern: /user|query|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "copilot",
    aiName: "Copilot",
    hosts: ["copilot.microsoft.com", "www.bing.com", "edgeservices.bing.com", "sydney.bing.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-testid*='assistant']",
      "[data-content='ai-message']",
      ".assistant-message",
      ".ac-container",
      "[class*='assistant']",
      "[class*='bot']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-testid*='user']",
      "[data-content='user-message']",
      ".user-message",
      "[class*='user']",
    ],
    contentSelectors: ["[data-testid='ai-message-body']", ".markdown", "[class*='markdown']", ".ac-textBlock", "[class*='message']", "[class*='content']"],
    assistantArticlePattern: /assistant|copilot|bing|answer|response/i,
    userArticlePattern: /user|you|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "poe",
    aiName: "Poe",
    hosts: ["poe.com", "www.poe.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-testid*='bot']",
      "[data-testid*='assistant']",
      "[class*='Message_bot']",
      "[class*='botMessage']",
      "[class*='assistant']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-testid*='user']",
      "[class*='Message_human']",
      "[class*='humanMessage']",
      "[class*='user']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='Message']",
      "[class*='message']",
      "[class*='content']",
    ],
    assistantArticlePattern: /assistant|bot|poe|answer|response/i,
    userArticlePattern: /user|human|you|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "mistral",
    aiName: "Mistral",
    hosts: ["chat.mistral.ai", "mistral.ai"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
    ],
    userSelectors: ["[data-message-author-role='user']", "[data-testid*='user']", ".user-message", "[class*='user']"],
    contentSelectors: [".markdown", "[class*='markdown']", "[class*='message']", "[class*='content']"],
    assistantArticlePattern: /assistant|mistral|answer|response/i,
    userArticlePattern: /user|you|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "meta",
    aiName: "Meta AI",
    hosts: ["meta.ai", "www.meta.ai"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
    ],
    userSelectors: ["[data-message-author-role='user']", "[data-testid*='user']", ".user-message", "[class*='user']"],
    contentSelectors: [".markdown", "[class*='markdown']", "[class*='message']", "[class*='content']"],
    assistantArticlePattern: /assistant|meta|answer|response/i,
    userArticlePattern: /user|you|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "doubao",
    aiName: "Doubao",
    hosts: ["doubao.com", "www.doubao.com"],
    assistantSelectors: [
      "div[data-testid='receive_message']",
      "[data-testid='receive_message']",
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      "[data-testid*='answer']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
      "[class*='answer']",
    ],
    userSelectors: [
      "div[data-testid='send_message']",
      "[data-testid='send_message']",
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      "[data-testid*='question']",
      ".user-message",
      "[class*='user']",
      "[class*='question']",
    ],
    contentSelectors: [
      "div[data-testid='message_text_content']",
      "[data-testid='message_text_content']",
      "[data-testid='message_content']",
      ".markdown",
      "[class*='markdown']",
      "[class*='message']",
      "[class*='content']",
      "[class*='answer']",
    ],
    assistantArticlePattern: /assistant|answer|response|豆包|回答/i,
    userArticlePattern: /user|question|prompt|用户|提问/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[aria-label*="停止"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "kimi",
    aiName: "Kimi",
    hosts: ["kimi.moonshot.cn", "kimi.com", "www.kimi.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
      "[class*='answer']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
      "[class*='question']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='message']",
      "[class*='content']",
      "[class*='answer']",
    ],
    assistantArticlePattern: /assistant|kimi|answer|response|回答/i,
    userArticlePattern: /user|question|prompt|用户|提问/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[aria-label*="停止"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "qwen",
    aiName: "Qwen",
    hosts: ["chat.qwen.ai", "qwen.ai", "tongyi.aliyun.com", "qianwen.aliyun.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
      "[class*='answer']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
      "[class*='question']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='message']",
      "[class*='content']",
      "[class*='answer']",
    ],
    assistantArticlePattern: /assistant|qwen|tongyi|answer|response|回答/i,
    userArticlePattern: /user|question|prompt|用户|提问/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[aria-label*="停止"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "yuanbao",
    aiName: "Yuanbao",
    hosts: ["yuanbao.tencent.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
      "[class*='answer']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
      "[class*='question']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='message']",
      "[class*='content']",
      "[class*='answer']",
    ],
    assistantArticlePattern: /assistant|yuanbao|answer|response|元宝|回答/i,
    userArticlePattern: /user|question|prompt|用户|提问/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[aria-label*="停止"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "chatglm",
    aiName: "ChatGLM",
    hosts: ["chatglm.cn", "www.chatglm.cn", "chatglm.com", "chat.z.ai"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
      "[class*='answer']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
      "[class*='question']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='message']",
      "[class*='content']",
      "[class*='answer']",
    ],
    assistantArticlePattern: /assistant|chatglm|z\.ai|answer|response|回答/i,
    userArticlePattern: /user|question|prompt|用户|提问/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[aria-label*="停止"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "ernie",
    aiName: "ERNIE",
    hosts: ["yiyan.baidu.com", "chat.baidu.com", "wenxin.baidu.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
      "[class*='answer']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
      "[class*='question']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='message']",
      "[class*='content']",
      "[class*='answer']",
    ],
    assistantArticlePattern: /assistant|ernie|yiyan|answer|response|文心|回答/i,
    userArticlePattern: /user|question|prompt|用户|提问/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[aria-label*="停止"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "huggingchat",
    aiName: "HuggingChat",
    hosts: ["huggingface.co"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
    ],
    contentSelectors: [".markdown", "[class*='markdown']", "[class*='message']", "[class*='content']"],
    assistantArticlePattern: /assistant|huggingchat|answer|response/i,
    userArticlePattern: /user|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "duck",
    aiName: "Duck.ai",
    hosts: ["duck.ai", "duckduckgo.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
      "[class*='answer']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
      "[class*='question']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='message']",
      "[class*='content']",
      "[class*='answer']",
    ],
    assistantArticlePattern: /assistant|duck|answer|response/i,
    userArticlePattern: /user|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
  {
    id: "you",
    aiName: "You.com",
    hosts: ["you.com", "www.you.com"],
    assistantSelectors: [
      "[data-message-author-role='assistant']",
      "[data-role='assistant']",
      "[data-testid*='assistant']",
      ".assistant-message",
      ".ai-message",
      "[class*='assistant']",
      "[class*='answer']",
    ],
    userSelectors: [
      "[data-message-author-role='user']",
      "[data-role='user']",
      "[data-testid*='user']",
      ".user-message",
      "[class*='user']",
      "[class*='question']",
    ],
    contentSelectors: [
      ".markdown",
      "[class*='markdown']",
      "[class*='message']",
      "[class*='content']",
      "[class*='answer']",
    ],
    assistantArticlePattern: /assistant|you\.com|answer|response/i,
    userArticlePattern: /user|question|prompt/i,
    streamingSelectors: ['[aria-label*="Stop"]', '[data-testid*="stop"]', "[class*='stop']"],
  },
];
export const FALLBACK_ADAPTER: PlatformAdapter = {
  id: "generic",
  aiName: "AI",
  hosts: [],
  assistantSelectors: [
    "[data-message-author-role='assistant']",
    "[data-role='assistant']",
    "[data-testid*='assistant']",
    ".assistant-message",
    ".ai-message",
    "[class*='assistant']",
  ],
  userSelectors: [
    "[data-message-author-role='user']",
    "[data-role='user']",
    "[data-testid*='user']",
    ".user-message",
    "[class*='user']",
  ],
  contentSelectors: [".markdown", "[class*='markdown']", "[class*='message']", "[class*='content']"],
  assistantArticlePattern: /assistant|answer|response/i,
  userArticlePattern: /user|question|prompt/i,
  streamingSelectors: ['[aria-label*="Stop"]', '[aria-label*="停止"]', '[data-testid*="stop"]', "[class*='stop']"],
};
